#!name = IT之家去广告
#!desc = 过滤 IT之家信息流广告和文末广告；默认移除全部横幅和置顶文章。必须搭配 QX 兼容脚本，不能使用 kelee 原 Loon 脚本。
#!openUrl = https://apps.apple.com/app/id570610859
#!author = 可莉, revised for Quantumult X
#!tag = 去广告
#!icon = https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/IThome.png

[rewrite_local]

^https?:\/\/dat\.ruanmei\.com\/ithome\/money\/acd\.json$ url reject
^https:\/\/napi\.ithome\.com\/api\/(news\/indexv2\/iphone\/\d+|topmenu\/getfeeds\?) url script-response-body https://raw.githubusercontent.com/S7venYoung/QuantumultX/refs/heads/master/js/IThome_remove_ads_qx.js

[mitm]

hostname = napi.ithome.com, dat.ruanmei.com
